version: "2"

services:
  apache-process:
    restart: always
    build: .
    environment:
      - VIRTUAL_HOST=process.ecrituresnumeriques.ca
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=process.ecrituresnumeriques.ca
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
      - HOME=/usr/local/apache2/cgi-bin
networks:
  default:
    external:
      name: root_default