version: "2"

services:
  apache-process:
    container_name: ecrinum-process
    build: .
    ports:
    - "9090:80"
    environment:
    - HOME=/usr/local/apache2/cgi-bin
    volumes:
     - ./data/:/usr/local/apache2/export/